name: build
on:
  push:
    tags-ignore: v*.*
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ninja
        run: sudo apt install -yqq ninja-build
      - name: configure gcc
        run: cmake -S . --preset=default -B build
      - name: configure clang
        run: cmake -S . --preset=ninja-clang -B clang
      - name: build gcc
        run: cmake --build build --config=Release
      - name: build clang
        run: cmake --build clang --config=Release
      - name: test
        run: cd build && ctest -C Release --output-on-failure

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake -S . --preset=vs22 -B build
      - name: build
        run: cmake --build build --config=Release
      - name: test
        run: cd build && ctest -C Release --output-on-failure

  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - name: install homebrew formulae
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: install ninja
        run: brew install ninja
      - name: update AppleClang to 14.0.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app/Contents/Developer
      - name: configure gcc
        run: cmake -S . --preset=default -B build
      - name: configure clang
        run: cmake -S . --preset=ninja-clang -B clang
      - name: build gcc
        run: cmake --build build --config=Release
      - name: build clang
        run: cmake --build clang --config=Release
      - name: test
        run: cd build && ctest -C Release --output-on-failure
